export default[
    '',
    ' xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxeeeex',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                      yyx',
    ' x                                                  xxxxxxx',
    ' x                                                        x',
    ' x                                                        x',
    ' x                                                        x',
    ' x                        v                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                xxxxxxxxxxxxxxxx',
    ' x                        x                               x',
    ' x          yyyy          x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x       yyyyyyyy                x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                        x                               x',
    ' x                 yyyyy  x                               x',
    ' xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvvvvvvvvvxxxxxxxxxxxxxxxx'
  ]
